### ISSUE TITLE
Pypi out of date

### ISSUE THREAD

**Issue by CMurtagh-LGTM** [jazzband/icalevents#100]
The [pypi](https://pypi.org/project/icalevents/) version is still at 0.1.25

**Comment by eigenmannmartin** [comment]
@CMurtagh-LGTM Once I get acces I will deploy new versions => https://github.com/jazzband/help/issues/252

**Comment by eigenmannmartin** [comment]
@ofekcensor I will update this weekend :-)
Sorry - totally ignored this todo item so far.

**Comment by eigenmannmartin** [comment]
@ofekcensor thank you for your patience! version 0.1.26 and 0.1.27 are released
