### ISSUE TITLE
parse_events is unordered?

### ISSUE THREAD

**Issue by funblaster22** [jazzband/icalevents#106]
I was using the `parse_events()` function, and didn't realize until a bit of experimentation that the return value from this function is not chronologically ordered. Would it be possible to sort the array [before returning](https://github.com/jazzband/icalevents/blob/c368ad8ec4981f58754faba3ef2668cd176d1350/icalevents/icalparser.py#L440) like this: `.sort(key=lambda i: i.start)` or [be documented](https://github.com/jazzband/icalevents/blob/c368ad8ec4981f58754faba3ef2668cd176d1350/icalevents/icalparser.py#L302)? Thanks!

**Comment by elizaaverywilson** [comment]
Should be [fixed](https://github.com/jazzband/icalevents/commit/6e1895775c6b404a1901b65e5eae22cbfe469fbd)
