### ISSUE TITLE
Recurring events and timezones branch

### ISSUE THREAD

**Issue by Herrner** [jazzband/icalevents#112]
Are the changes that have been made in the [recurring-events-and-timezones](https://github.com/jazzband/icalevents/tree/recurring-events-and-timezones) branch planned to make it into master anytime? I'm getting the (known and documented) errors when parsing Google calendars, and these disappear when using the changes from that fork (plus [one](https://github.com/Herrner/icalevents/pull/2) I added myself).

**Comment by adamehirsch** [comment]
Seconded; these changes are working well for me.
