### ISSUE TITLE
Dependencies pinned to outdated versions

### ISSUE THREAD

**Issue by xi** [jazzband/icalevents#123]
As part of #83, some dependencies were pinned to specific versions. For example, `icalendar` is currently pinned to [4.0.9](https://github.com/collective/icalendar/blob/master/CHANGES.rst#409-2021-10-16), a version that is more than one year old.

I think there are two issues here:

- dependencies are not updated regularly
- dependencies are pinned down to the exact version so bug fix releases of the dependencies cannot be installed without a new release of `icalevents` itself. The common fix is to only pin the major or minor version, but not the patch version.

**Comment by eigenmannmartin** [comment]
True - we should enable renovate :-)

**Comment by MinchinWeb** [comment]
I ran into this issue today because another library want to install the current version of `pytz` (2023.3), but this is pinned to a two year old version (2021.3).

**Comment by JamieMagee** [comment]
I also ran into this today.

@eigenmannmartin I can help you configure Renovate if you need any help.

**Comment by eigenmannmartin** [comment]
Thank you very much for this issue - I have updated the deps for now and will check that dependapot/renovate will update dependencies in the future. :-)

**Comment by xi** [comment]
The second issue still exists: It should not be necessary to updae `icalevents` just to get an updated version of `icalendar`. The dependency on `icalendar` should use the `^` operator, just like all other dependencies.

**Comment by xi** [comment]
Finally fixed in #145.
