### ISSUE TITLE
Docs missing `events()`

### ISSUE THREAD

**Issue by csm10495** [jazzband/icalevents#126]
Hey folks,

The [docs](https://icalevents.readthedocs.io/en/latest/) seem to be missing documentation for: 

`icalevents.events()`.

Particularly this block is empty: https://icalevents.readthedocs.io/en/latest/#icalevents-icalevents-module

**Comment by leingang** [comment]
I also noticed this when I went looking for details of the `events()` function. The module is documented well, but it's not being processed into documentation for some reason.

**Comment by eigenmannmartin** [comment]
Thanks for pointing this out, it is fixed now :-)
