### ISSUE TITLE
"events" method does not return events "description" for recurring events 

### ISSUE THREAD

**Issue by debackel** [jazzband/icalevents#13]
The events method of the icalevents class does not return the "description" parameter of events for occurences of a recurring event.

See attached files:
1/ The calendar
2/ The code used for testing
3/ The output of the code

[MyCal1.txt](https://github.com/irgangla/icalevents/files/1756522/MyCal1.txt)
[essai2.txt](https://github.com/irgangla/icalevents/files/1756523/essai2.txt)
[output2.txt](https://github.com/irgangla/icalevents/files/1756527/output2.txt)

**Comment by dlichtistw** [comment]
Glad you mentioned that. The description is lost when creating recurring copies of the master event. An additional line in the `copy_to` method did fix it for me.

**Comment by PabloCastellano** [comment]
Doesn't 8572fafa15eb3fff4a1ae1971205d98f0a910bc4 fix it?

**Comment by eigenmannmartin** [comment]
should be fixed, closing old issue
