### ISSUE TITLE
Can't find the docs??

### ISSUE THREAD

**Issue by ghost** [jazzband/icalevents#31]
As above, really - there's a two-line "usage" in README, but I can't find any documentation of how you actually use it..

**Comment by devrosx** [comment]
yes some simple test would be good, I want to fetch upcoming x days as list of events, but can't find any doc how to use this library...

**Comment by tonimelisma** [comment]
Hey @digitaltoast @devrosx did you find any documentation? Is there any way to use this library besides reading the source?

**Comment by GrandMoff100** [comment]
Yeah, there isn't any documentation it seems... this is unfortunate. TIme to do some source reading I guess...

**Comment by jameselks** [comment]
As a non-developer it took me a while to get my head around it. Don't install with `pip` because the version is out of date. Clone this repository and add to your virtual environment using setup.py

Here's what I came up with:

```python
from icalevents.icalevents import events
from datetime import datetime, timedelta
import pytz

url = 'https://outlook.office365.com/owa/calendar/....ics'

my_timezone = pytz.timezone('Australia/Melbourne')
now = datetime.now()
future = now + timedelta(hours=24)

es = events(url, start=now, end=future)

for e in es:
    print(e.start.astimezone(my_timezone).strftime("%Y-%m-%d %H:%M") + ' ' + e.summary )
   #You can see all of the object properties in icalparser.py - e.g. uid, summary description, start, end...
```

**Comment by GrandMoff100** [comment]
Awesome! Thank you.

**Comment by eigenmannmartin** [comment]
an example can be found here: https://icalevents.readthedocs.io/en/latest/

closing this old issue :-)
