### ISSUE TITLE
Yearly repeating events raise an error

### ISSUE THREAD

**Issue by ndw** [jazzband/icalevents#47]
Consider this fragment:
```
RRULE:FREQ=YEARLY;INTERVAL=1;UNTIL=20190328
DTEND;VALUE=DATE:20170330
DTSTART;VALUE=DATE:20170329
```

When `icalevents` loads this event, it will normalize the `date` into a `datetime`. But when `dateutil.rrule` is called subsequently, it will object:

```
RRULE UNTIL values must be specified in UTC when DTSTART is timezone-aware
```

Unfortunately, there are several places where start and end times are compared and the possibility of a mixture of `date` and `datetime` objects isn't handled.

**Comment by Currywurst** [comment]
I got this too and fixed it by adding few lines after event.all_day and before   try: event.location in the file icalparser.py:

    event.all_day = type(component.get('dtstart').dt) is date

`

    if component.get('rrule'):

        event.recurring = True
        if( component.get('rrule').get('until') ):
            iIndexListUntil = 0
            for x in component.get('rrule').get('until'):
                currentUntil = component.get('rrule').get('until')[iIndexListUntil]
                if not hasattr(currentUntil, 'tzinfo'):
                    component.get('rrule').get('until')[iIndexListUntil] = normalize( currentUntil, tz=tz )
                iIndexListUntil + 1
`
    try:
        event.location = str(component.get('location'))
    except UnicodeEncodeError as e:
        event.location = str(component.get('location').encode('utf-8'))

So it adds timezone informations if until does not have one

**Comment by kujiy** [comment]
Weekly would occur the same also
```
DTSTART;VALUE=DATE:20190706
DTEND;VALUE=DATE:20190713
RRULE:FREQ=WEEKLY;INTERVAL=5;BYDAY=SA
```
I haven't looked deeply yet but just let me take a memo.

**Comment by cancan101** [comment]
This still seems to be an issue even on 0.1.25:
With this rule string:
```
FREQ=WEEKLY;UNTIL=20200627;BYDAY=MO,WE;WKST=SU
```

**Comment by cancan101** [comment]
I ended up using:
```python
        def fix_rule(rule):
            if 'UNTIL' in rule:
                rule['UNTIL'] = [normalize(r, tz=tz) for r in rule['UNTIL']]
            return rule

        # If dtstart is a datetime, make sure it's in a timezone.
        rdtstart = component['dtstart'].dt
        if type(rdtstart) is datetime:
            rdtstart = normalize(rdtstart, tz=tz)
            rrules = [fix_rule(x) for x in rrules]```
