### ISSUE TITLE
How to iterate over recurring events with a time constraint?

### ISSUE THREAD

**Issue by wsw70** [jazzband/icalevents#60]
I could not find any documentation so sorry if this is explained somewhere.

I accessed a Google Calendar URL to retrieve a calendar. It has two recurring events. What I get as a reply is a list of these two events.

- how can I access the actual, atomic events (say that the event is repeated every Monday, how do I get a list of these Monday events?)
- how can I time-constrain the query (for the example above, getting all the events between now and a month from now should give ~4 events, generated from the single recurring events)

**Comment by ndw** [comment]
I don't think there's a way to get a projection for any given event, but if you iterate over the Monday's that you're interested in and ask "what events occur on this day", I think you can get the results.

**Comment by eigenmannmartin** [comment]
You can use the uid. All instances of the expanded (rrule) event have the same uid as the original event.

Please tell me if this is still pending.
