### ISSUE TITLE
Some events are missing if all_day event is within list

### ISSUE THREAD

**Issue by dkuschmierz** [jazzband/icalevents#74]
Consider the following settings:
startdate: 01.12.2020 00:00:00
enddate: 31.12.2020 23:59:59

Events:
10.12.2020 18:00:00 EventA
22.12.2020 AllDay EventB
31.12.2020 17:00:00 EventC

While iterating through the calendar, the enddate-settings are reseted during the allday-event to 31.12.2020 00:00:00 and then EventC is missing in the list!

**Comment by dkuschmierz** [comment]
This PR fixes the behavior:

https://github.com/irgangla/icalevents/pull/73

**Comment by eigenmannmartin** [comment]
closed by: https://github.com/jazzband/icalevents/pull/136
