### ISSUE TITLE
[Discussion] Transfer ownership of project to jazzband or similar?

### ISSUE THREAD

**Issue by Hultner** [jazzband/icalevents#81]
## Background
I was talking with Martin Eigenmann (@eigenmannmartin) in private. 
He reached out to me since he's got some contributions he want to merge (#80). I've tried for a while to review and merge PRs but without any ability to cut new releases which are pushed to PyPi it started to feel a bit pointless after a while. 
 
## Suggestion
Move ownership of the project to https://jazzband.co/ (or similar) collective ownership organisation. This way we could continue to maintain the project easier. 
@irgangla: I'd love to hear your thoughts on this? I'm no longer a user of the library so I'm not that heavily invested these days but it's a bit sad if the project would slowly be weathering into obsolesce without any new releases. For these kinds of libraries I'm very much for the collective ownership model.

**Comment by eigenmannmartin** [comment]
I am using this library for a project currently, and I am planning to keep using it for quite some time. If there is any chance I'd like to chime in and help to maintain icalevents.

I'd also suggest, because icalevents is quite useful for many use cases, that we make sure that if there are developments/improvements, that there is the ability to release new versions. Therefore, https://jazzband.co/ might really be a good fit I think.

**Comment by eigenmannmartin** [comment]
@irgangla Thomas is there anything I can support you with? :smiley:

**Comment by irgangla** [comment]
@eigenmannmartin @Hultner
Sorry for the very late reply, I have just too much work to take care of old private projects. Moving to https://jazzband.co/ sounds good. :)

**Comment by irgangla** [comment]
@eigenmannmartin I also added you as contributor to this repo.

**Comment by irgangla** [comment]
@eigenmannmartin @Hultner If the automation still works, publishing a new release in the repo will also push it to PyPi. Are you not able to publish a new release in the repo?
If not, please give me some release notes, then I can do it.

**Comment by Hultner** [comment]
@irgangla That’s understandable and why I also think Jazzband is a good idea. @eigenmannmartin do you have any knowledge of how the transfer of ownership process would be initiated? I guess we need to talk with a representative from Jazzband.

**Comment by irgangla** [comment]
I joined jazzboard and according to the homepage, their bot should invite me to the organization. Then I should be able to request a transfer by using the Github transfer feature.

**Comment by Hultner** [comment]
> @eigenmannmartin @Hultner If the automation still works, publishing a new release in the repo will also push it to PyPi. Are you not able to publish a new release in the repo?
> If not, please give me some release notes, then I can do it.

Ah I see, I was no aware that the release process was automated. I can draft new releases. That's great :)

**Comment by Hultner** [comment]
> I joined jazzboard and according to the homepage, their bot should invite me to the organization. Then I should be able to request a transfer by using the Github transfer feature.

Cool, then it's already in motion :)

**Comment by irgangla** [comment]
@Hultner I hope the automation is still working. See https://github.com/irgangla/icalevents/blob/master/.travis.yml
If not, please ping me, then I will try to fix it.

**Comment by eigenmannmartin** [comment]
@irgangla @Hultner Let me know if there is anything I can assist you :-)

**Comment by irgangla** [comment]
Repo transfer to jazzband started.
@eigenmannmartin  Please provide your PiPy username if I shall add you as maintainer there as well.

**Comment by eigenmannmartin** [comment]
@irgangla sure :-)  => eigenmannmartin
